# Generated by Django 4.1.1 on 2023-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
