# Generated by Django 4.2 on 2023-09-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_age_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
