# Generated by Django 4.2 on 2023-09-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vendor_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='age',
            new_name='address',
        ),
    ]
