# Generated by Django 4.2 on 2023-06-06 17:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_slug_alter_additional_information_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
