# Generated by Django 4.2 on 2023-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_vendor_name_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
    ]
